#!/bin/bash
shoes_host="http://shoes.mvmanila.com"
shoes_arch="osx"
shoes_path="/public/select/osx.rb"
APPPATH="${0%/*}"
this_dir=$APPPATH
echo $this_dir >find.me
shoes_dir="$HOME/.shoes/walkabout" 
shoes_home="/Applications/Shoes.app/Contents/MacOS/shoes-bin"
if [ ! -x  $shoes_home ] ; then
  shoes="$shoes_dir/shoes"
  mkdir -p $HOME/.shoes/install
  mkdir -p $shoes_dir
  $this_dir/shoes-osx-install $shoes_host $shoes_path
  # find and untar - assume only one tgz copy to /Applications
  # (might be different filesystems). Delete from this directory
  cd $HOME/.shoes/install
  tar -xf shoes*.tgz
  cp -a Shoes.app /Applications
  rm shoes*.tgz
  rm -r Shoes.app
  cd $this_dir
fi
$this_dir/guess-launch
